version: "2.4"

services:
  tinyfecVPN:
    cap_add:
      - NET_ADMIN
    command: >-
      -c
      -r ${SERVER}:4096
      -k ${PASSWORD}
      --keep-reconnect
    container_name: tinyfecVPN
    image: suieu/tinyfecvpn
    networks:
      - tinyfecVPN
    restart: always
    sysctls:
      net.ipv4.ip_forward: 1

networks:
  tinyfecVPN:
    external: true
